name: Style Checker and Prettify Code
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use an appropriate Node.js version

      - name: Install Dependencies
        run: npm install -g prettier

      - name: Prettify Code
        run: prettier --write "**/*.{js,md}"

